/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateFreightBiddingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "awardJob"
      | "closeBidding"
      | "freightJobs"
      | "getBidInfo"
      | "getBidders"
      | "getJobInfo"
      | "jobBidders"
      | "jobBids"
      | "jobCounter"
      | "owner"
      | "postJob"
      | "protocolId"
      | "revealBid"
      | "submitBid"
      | "verifiedCarriers"
      | "verifiedShippers"
      | "verifyCarrier"
      | "verifyShipper"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidRevealed"
      | "BidSubmitted"
      | "JobAwarded"
      | "JobPosted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "awardJob",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeBidding",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freightJobs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidInfo",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobBidders",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobBids",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jobCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postJob",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealBid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedCarriers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedShippers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCarrier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyShipper",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "awardJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeBidding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freightJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBidInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBidders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJobInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobBidders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobBids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobCounter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revealBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifiedCarriers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedShippers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCarrier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyShipper",
    data: BytesLike
  ): Result;
}

export namespace BidRevealedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    carrier: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, carrier: string, price: bigint];
  export interface OutputObject {
    jobId: bigint;
    carrier: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [jobId: BigNumberish, carrier: AddressLike];
  export type OutputTuple = [jobId: bigint, carrier: string];
  export interface OutputObject {
    jobId: bigint;
    carrier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobAwardedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    carrier: AddressLike,
    finalPrice: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    carrier: string,
    finalPrice: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    carrier: string;
    finalPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobPostedEvent {
  export type InputTuple = [jobId: BigNumberish, shipper: AddressLike];
  export type OutputTuple = [jobId: bigint, shipper: string];
  export interface OutputObject {
    jobId: bigint;
    shipper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateFreightBidding extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateFreightBidding;
  waitForDeployment(): Promise<this>;

  interface: PrivateFreightBiddingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  awardJob: TypedContractMethod<
    [_jobId: BigNumberish, _carrier: AddressLike],
    [void],
    "nonpayable"
  >;

  closeBidding: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  freightJobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        origin: string;
        destination: string;
        cargoType: string;
        weight: bigint;
        volume: bigint;
        deadline: bigint;
        biddingEndTime: bigint;
        shipper: string;
        status: bigint;
        finalPrice: bigint;
        isPrivate: boolean;
      }
    ],
    "view"
  >;

  getBidInfo: TypedContractMethod<
    [_jobId: BigNumberish, _carrier: AddressLike],
    [
      [boolean, boolean, bigint] & {
        hasSubmitted: boolean;
        isRevealed: boolean;
        revealedPrice: bigint;
      }
    ],
    "view"
  >;

  getBidders: TypedContractMethod<[_jobId: BigNumberish], [string[]], "view">;

  getJobInfo: TypedContractMethod<
    [_jobId: BigNumberish],
    [
      [string, string, bigint] & {
        origin: string;
        destination: string;
        status: bigint;
      }
    ],
    "view"
  >;

  jobBidders: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  jobBids: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, boolean, boolean, bigint, bigint] & {
        encryptedPrice: string;
        hasSubmitted: boolean;
        isRevealed: boolean;
        revealedPrice: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  jobCounter: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  postJob: TypedContractMethod<
    [_origin: string, _destination: string, _cargoType: string],
    [bigint],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  revealBid: TypedContractMethod<
    [_jobId: BigNumberish, _price: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitBid: TypedContractMethod<
    [_jobId: BigNumberish, _price: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifiedCarriers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  verifiedShippers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  verifyCarrier: TypedContractMethod<
    [_carrier: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyShipper: TypedContractMethod<
    [_shipper: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "awardJob"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _carrier: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeBidding"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "freightJobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        origin: string;
        destination: string;
        cargoType: string;
        weight: bigint;
        volume: bigint;
        deadline: bigint;
        biddingEndTime: bigint;
        shipper: string;
        status: bigint;
        finalPrice: bigint;
        isPrivate: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBidInfo"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _carrier: AddressLike],
    [
      [boolean, boolean, bigint] & {
        hasSubmitted: boolean;
        isRevealed: boolean;
        revealedPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBidders"
  ): TypedContractMethod<[_jobId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getJobInfo"
  ): TypedContractMethod<
    [_jobId: BigNumberish],
    [
      [string, string, bigint] & {
        origin: string;
        destination: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobBidders"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobBids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, boolean, boolean, bigint, bigint] & {
        encryptedPrice: string;
        hasSubmitted: boolean;
        isRevealed: boolean;
        revealedPrice: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postJob"
  ): TypedContractMethod<
    [_origin: string, _destination: string, _cargoType: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealBid"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifiedCarriers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifiedShippers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyCarrier"
  ): TypedContractMethod<[_carrier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyShipper"
  ): TypedContractMethod<[_shipper: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BidRevealed"
  ): TypedContractEvent<
    BidRevealedEvent.InputTuple,
    BidRevealedEvent.OutputTuple,
    BidRevealedEvent.OutputObject
  >;
  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "JobAwarded"
  ): TypedContractEvent<
    JobAwardedEvent.InputTuple,
    JobAwardedEvent.OutputTuple,
    JobAwardedEvent.OutputObject
  >;
  getEvent(
    key: "JobPosted"
  ): TypedContractEvent<
    JobPostedEvent.InputTuple,
    JobPostedEvent.OutputTuple,
    JobPostedEvent.OutputObject
  >;

  filters: {
    "BidRevealed(uint256,address,uint32)": TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;
    BidRevealed: TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;

    "BidSubmitted(uint256,address)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "JobAwarded(uint256,address,uint256)": TypedContractEvent<
      JobAwardedEvent.InputTuple,
      JobAwardedEvent.OutputTuple,
      JobAwardedEvent.OutputObject
    >;
    JobAwarded: TypedContractEvent<
      JobAwardedEvent.InputTuple,
      JobAwardedEvent.OutputTuple,
      JobAwardedEvent.OutputObject
    >;

    "JobPosted(uint256,address)": TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;
    JobPosted: TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;
  };
}
